### ISSUE TITLE
Extend free text date validation options to include ISO8601, and save the encoding of the date value if known

### ISSUE THREAD

**Issue by patdunlavey** [esmero/webform_strawberryfield#112]
With the [addition of EDTF validation](https://github.com/esmero/webform_strawberryfield/pull/104), we can ensure that free text dates are encoded as edtf. This proposal has two parts:
1. Add an option for validating the date string as ISO8601, 
2. Add a hidden field to the WebformMetadataDate element that saves an encoding value - edtf, iso8601, etc - if known based on the validation.
and maybe...
3. Detection of free text date encoding by validating against the edtf and ISO8601 validation functions could occur on all submissions of this form element, not just when validation is required, and be used to set the encoding value. 

Having the encoding known would be useful in later interpretation of the freeform date value, as when generating MODS, indexing in solr, or reformatting for display.

**Comment by DiegoPino** [comment]
@patdunlavey I do not know enough of EDTF (asking @alliomeria here too) but here is a back question. Is a ISO8601 point date a valid EDTF one? If this is yes, then we may not need an extra validation (the idea of free form is to allow non ISO to be used when ISO is already possible in the Start/ End dates (and yes, we may be stricter validating there, I agree).

Regarding detection/validating on submission (you mean webform) may be complex because It would not give the user the chance of correcting. If that is what is attempted, but also here Is a counter idea:

Where do you need to know if the date is what you expect?

- In a Twig template (when showing or AMI ingesting). That can be solved adding an extra extension (a Twig TEST) like this `is_edtf` and you can also have a twig extension that parses EDTF into other values (human readable) if that is needed. 
- In Solr Indexing. The new Key Name provider would just need to have a method that detects first if its an EDTF and if so tries to come up with ISO valid alternatives (if any), if it fails, try with a simple String to Date parsing and then to ISO and if all that fails, refuse to index and do not expose the value to Solr/SBF property

Not having a marker (which type of date is input) could be beneficial for ingesting and also for UI interaction

But I understand there can be other use cases I have not covered and happy to discuss them and find a solution.

**Comment by DiegoPino** [comment]
Checking back on you. If the LoC ETDF site is right, any ISO8601 is in fact a valid ETDF, which means we do not need to mark what the user added.

**Comment by DiegoPino** [comment]
@patdunlavey checking back on you. Did my response clarify this? Will close in 24hrs in case there are no updates. Thx

**Comment by patdunlavey** [comment]
Sorry for no response!! Yes, we're good to close this.
